{% set version = "0.16.0" %}

package:
  name: cartopy
  version: {{ version }}

source:
  url: https://github.com/SciTools/cartopy/archive/v{{ version }}.tar.gz
  sha256: 688606f2a9782f14997d57142fbec89d4e8f10cd3dcb4c7c3b0d0a2dd7098cc8
  patches:
    # Cartopy geos_c patch.
    - cartopy.win.patch  # [win]

build:
  number: 0

requirements:
  build:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - msinttypes  # [win]
    - geos 3.6.2
    - proj4 4.9.3
  run:
    - python
    - numpy >=1.11
    - six
    - pillow
    - owslib
    - proj4 4.9.3
    - geos 3.6.2
    - shapely
    - scipy
    - pyshp
    - matplotlib
    - pyepsg

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://scitools.org.uk/cartopy
  license: GNU LGPL
  license_file: COPYING
  summary: 'A library providing cartographic tools for python.'

extra:
  recipe-maintainers:
    - marqh
    - ocefpaf
    - pelson
    - dopplershift
