{% set version = "0.18.0" %}

package:
  name: cartopy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/Cartopy/Cartopy-{{ version }}.tar.gz
  sha256: 7ffa317e8f8011e0d965a3ef1179e57a049f77019867ed677d49dcc5c0744434

build:
  skip: true  # [win and vc<14]
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - msinttypes  # [win and vc<14]
    - proj
    - gdal
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pillow >=1.7.8
    - owslib >=0.8.11
    - shapely >=1.5.6
    - scipy >=0.10
    - pyshp >=1.1.4
    - matplotlib-base >=1.5.1
    - pyepsg >=0.4.0
    - proj
    - gdal

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs

about:
  home: http://scitools.org.uk/cartopy
  license: LGPL-3
  license_file: 
    - COPYING
    - COPYING.LESSER
  summary: A library providing cartographic tools for python
  dev_url: https://github.com/SciTools/cartopy
  doc_url: https://scitools.org.uk/cartopy/docs/latest/

extra:
  recipe-maintainers:
    - marqh
    - ocefpaf
    - pelson
    - dopplershift
    - xylar
