{% set name = "cartopy" %}
{% set version = "0.24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01c910d5634c69a7efdec46e0a17d473d2328767f001d4dc0b5c4b48e585c8bd

build:
  # s390x: this package is not in the SoW
  skip: True  # [(win and vc<14) or s390x or py<310]
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{version}}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
    - cython >=0.29.24
    - numpy 2.0 # [py<313]
    - numpy 2.1 # [py==313]
  run:
    - python
    - numpy >=1.23
    - shapely >=1.8
    - packaging >=21
    - pyshp >=2.3
    - matplotlib-base >=3.6
    - pyproj >=3.1.0
  run_constrained:
    - scipy >=1.9
    - pillow >=9.1
    - owslib >=0.27.0

test:
  requires:
    - pip
    - pytest >=5.1.2
    - pytest-xdist
    - scipy >=1.3.1
  commands:
    - python -c "import cartopy.crs as ccrs; import matplotlib.pyplot as plt; ax = plt.axes(projection=ccrs.PlateCarree())"
    - pip check
    - pytest -ra -n 4 --pyargs cartopy

about:
  home: https://scitools.org.uk/cartopy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library providing cartographic tools for python
  description: |
    Cartopy is a Python package designed for geospatial data processing in order to produce maps and other geospatial data analyses.

    Cartopy makes use of the powerful PROJ, NumPy and Shapely libraries and includes a programmatic interface built on top of Matplotlib for the creation of publication quality maps.
  dev_url: https://github.com/SciTools/cartopy
  doc_url: https://scitools.org.uk/cartopy/docs/latest/

extra:
  recipe-maintainers:
    - marqh
    - ocefpaf
    - pelson
    - dopplershift
    - xylar
