{% set version = "0.21.1" %}

package:
  name: cartopy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/Cartopy/Cartopy-{{ version }}.tar.gz
  sha256: 89d5649712c8582231c6e11825a04c85f6f0cee94dbb89e4db23eabca1cc250a

build:
  # s390x is missing geos and this package is not in the SoW
  skip: True  # [(win and vc<14) or s390x or py<38]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
    - cython
    - numpy   1.19  # [py<310]
    - numpy   1.21  # [py==310]
    - numpy   1.23  # [py>=311]
    - geos    3.9.1
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - shapely >=1.6.4
    - pyshp >=2.1
    - geos >=3.7.2
    # including matplotlib-base even though it's optional upstream
    - matplotlib-base >=3.1
    - scipy >=1.3.1
    - pyproj >=3.0.0
    - ucrt  # [win]

test:
  requires:
    - pip
    - pytest
  commands:
    - python -c "import cartopy.crs as ccrs; import matplotlib.pyplot as plt; ax = plt.axes(projection=ccrs.PlateCarree())"
    - pip check
    - python -m pytest --pyargs --doctest-modules cartopy
about:
  home: https://scitools.org.uk/cartopy
  license: LGPL-3.0
  license_family: GPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: A library providing cartographic tools for python
  description: |
    Cartopy is a Python package designed for geospatial data processing in order to produce maps and other geospatial data analyses.

    Cartopy makes use of the powerful PROJ, NumPy and Shapely libraries and includes a programmatic interface built on top of Matplotlib for the creation of publication quality maps.
  dev_url: https://github.com/SciTools/cartopy
  doc_url: https://scitools.org.uk/cartopy/docs/latest/

extra:
  recipe-maintainers:
    - marqh
    - ocefpaf
    - pelson
    - dopplershift
    - xylar
