{% set version = "0.15.1" %}

package:
  name: cartopy
  version: {{ version }}

source:
  url: https://github.com/SciTools/cartopy/archive/v{{ version }}.tar.gz
  sha256: c2221eaf8cb3827b026a398374f3b2e9431aa77fdf95754229232ef5236221ed
  patches:
    # Cartopy geos_c patch.
    - cartopy.win.patch  # [win]
    # Library changes taken from https://github.com/SciTools/cartopy/pull/773
    - matplotlib2.patch

build:
  number: 4

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - msinttypes  # [win]
    - geos 3.5.1
    - proj4 4.9.3
  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - six
    - pillow
    - owslib
    - proj4 4.9.3
    - geos 3.5.1
    - shapely
    - scipy
    - pyshp
    - matplotlib
    - pyepsg

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs
  commands:
    - conda inspect linkages -p $PREFIX cartopy  # [not win]
    - conda inspect objects -p $PREFIX cartopy  # [osx]

about:
  home: http://scitools.org.uk/cartopy
  license: GNU LGPL
  license_file: COPYING
  summary: 'A library providing cartographic tools for python.'

extra:
  recipe-maintainers:
    - marqh
    - ocefpaf
    - pelson
    - dopplershift
