{% set version = "0.18.0" %}

package:
  name: cartopy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/Cartopy/Cartopy-{{ version }}.tar.gz
  sha256: 7ffa317e8f8011e0d965a3ef1179e57a049f77019867ed677d49dcc5c0744434
  patches:
    # Cartopy geos_c patch.
    - proj6-fix.patch
    - cartopy.win.patch  # [win]

build:
  skip: true  # [win and vc<14]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - msinttypes  # [win and vc<14]
    - geos
    - proj
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - six
    - pillow
    - owslib
    - proj
    - geos
    - shapely
    - scipy
    - pyshp
    - matplotlib-base
    - pyepsg
    - pykdtree

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs

about:
  home: http://scitools.org.uk/cartopy
  license: LGPL-3.0
  license_file: COPYING
  summary: A library providing cartographic tools for python

extra:
  recipe-maintainers:
    - marqh
    - ocefpaf
    - pelson
    - dopplershift
    - xylar
