{% set version = "0.15.0" %}

package:
  name: cartopy
  version: {{ version }}

source:
  fn: cartopy-{{ version }}.tar.gz
  url: https://github.com/SciTools/cartopy/archive/v{{ version }}.tar.gz
  sha256: fdee52cc2f259785a7744951ba43f339d33d517a5ec9cee301a33a267c60fd65
  patches:
    - cartopy.win.patch  # [win]

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - msinttypes  # [win]
    - numpy x.x
    - cython
    - geos 3.5.*
    - proj4 4.9.3
  run:
    - python
    - numpy x.x
    - six
    - pillow
    - owslib
    - proj4 4.9.3
    - geos 3.5.*
    - shapely
    - scipy
    - pyshp
    - matplotlib
    - pyepsg

test:
  requires:
    - nose
    - pep8
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs
  commands:
    - conda inspect linkages -p $PREFIX cartopy  # [not win]
    - conda inspect objects -p $PREFIX cartopy  # [osx]

about:
  home: http://scitools.org.uk/cartopy
  license: GNU LGPL
  license_file: COPYING
  summary: 'A library providing cartographic tools for python.'

extra:
  recipe-maintainers:
    - marqh
    - ocefpaf
    - pelson
