{% set version = "0.21.1" %}

package:
  name: cartopy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/C/Cartopy/Cartopy-{{ version }}.tar.gz
  patches:
    - port310.patch
  sha256: 89d5649712c8582231c6e11825a04c85f6f0cee94dbb89e4db23eabca1cc250a

build:
  skip: True  # [win and vc<14]
  error_overlinking: true
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - cython
    - numpy
    - msinttypes  # [win and vc<14]
    # proj and geos are needed as dependencies even though not listed upstream
    - proj <8.0.0  # newer versions removed required proj_api.h
    - geos
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - shapely >=1.5.6
    - pyshp >=1.1.4
    - six >=1.3.0
    # proj and geos are needed as dependencies even though not listed upstream
    - proj <8.0.0  # newer versions removed required proj_api.h
    - geos
    # including matplotlib-base even though it's optional upstream
    - matplotlib-base >=1.5.1
    - scipy >=0.10

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs
  commands:
    - python -c "import cartopy.crs as ccrs; import matplotlib.pyplot as plt; ax = plt.axes(projection=ccrs.PlateCarree())"

about:
  home: http://scitools.org.uk/cartopy
  license: LGPL-3
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: A library providing cartographic tools for python
  dev_url: https://github.com/SciTools/cartopy
  doc_url: https://scitools.org.uk/cartopy/docs/latest/

extra:
  recipe-maintainers:
    - marqh
    - ocefpaf
    - pelson
    - dopplershift
    - xylar
