travis:
  secure:
    BINSTAR_TOKEN: zyaZK3IiU8K8yNnSQpKnUA7IW8dhL/fm1WHur7uPRbqN7m2HGFOHk/h6QWcpFgeQh/OOW4e2vGyDFFZ7DiU9xI7AdqeDrAMkV6aB44gGSdtfgFq07uszC3qS/i1uPDVJ9QsaNA8ZPMGW7Yx2VglZwu3nqUvS6DO1irXSyTjwokPHkq9ko8CyYavYYx+oFAJH2nYKa/K48QrJDIMymbRmKYlxCDBssvPtmUQHhxluWW3EXX0dr4wAD1YsCok2yt/31hKuDytq5yMe69WysglJrkvxxY31y5vmSoeSyFHxRQ1LUZNsSkVx5V4NCqbu7VRFokblzMCOayALsJOibaF2saW4pAk17fZdDF/GhkDiC9k7nUS8e+xgLAE3eMyWPf939UScb4yer0AIIIgnEMLeNG40sN3rgn0wnY+4N7qiDvUSxE8JBcxJYhW9Iu8sOa0Gv2bfcf9huoxRPxcXTkRNMY9YwPwzys4xGRHF6uI5QazOd0m1nYZO75So5WHK2PMGYOy9aS2iJixPVhctZ8YMBqt78kN9hLkjfUCk9T2Hscni6I4waoFvWbArGKL5blEpBex3Yf/3Op53JZ90YnginDCLaxonCahiJhy7O6ot7DwTAcRWsKPqFILkLNnXV6ybnfSP7o/Dr965JqxKxWrZOMBIxjkmjvzBhtKFyJkQcHs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
